### ISSUE TITLE
Unit tests are failing with assertion fails

### ISSUE THREAD

**Issue by DnPlas** [canonical/kubeflow-dashboard-operator#141]
Some test cases are failing due to:

```
======================================================================================================== short test summary info ========================================================================================================
FAILED tests/unit/test_operator.py::TestCharm::test_create_resources_success - AssertionError: Expected 'apply' to have been called once. Called 0 times.
FAILED tests/unit/test_operator.py::TestCharm::test_main - AssertionError: Expected 'apply' to have been called.
FAILED tests/unit/test_sidebar_lib.py::TestDashboardLink::test_location_validation[invalid-location-context_raised4] - Failed: DID NOT RAISE <class 'ValueError'>
===================================================================================================== 3 failed, 39 passed in 0.45s ======================================================================================================
ERROR: InvocationError for command /home/ubuntu/kubeflow-dashboard-operator/.tox/unit/bin/coverage run --source=/home/ubuntu/kubeflow-dashboard-operator/src/ -m pytest --ignore=/home/ubuntu/kubeflow-dashboard-operator/tests/integration -vv --tb native (exited with code 1)
________________________________________________________________________________________________________________ summary ________________________________________________________________________________________________________________
ERROR:   unit: commands failed
```

Latest run in #140 is an example of this.

**Comment by phoevos** [comment]
The first 2 errors show when trying to update from `ops 1.5` to `ops 2+` and they are to be expected.

In both of these cases, we do `harness.begin()` and manually trigger the `install` event. In order for this to work, we have to manually enable container connectivity, using `harness.set_can_connect(container, True)`.

This doesn't show elsewhere, because we generally use `begin_with_initial_hooks`, which triggers the `on-pebble-ready` event that marks the container as connected.

**Comment by phoevos** [comment]
The last error is irrelevant and only appeared due to a mixup with the dashboard lib, the v2 of which has been published, but does not include the following lines:
https://github.com/canonical/kubeflow-dashboard-operator/blob/a4ea06861baf9ae8f5c3c4eaa512fd24ebe71b3f/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py#L109-L113
